### ISSUE TITLE
JOSM Plugin to have "next" and "previous" buttons

### ISSUE THREAD

**Issue by MikeTho16** [openstreetview/josm-plugin#2]
It would be nice if while viewing an image you could click a button to go to either the next or previous image in the track and if the user would have the option of having the map automatically pan to the location of the newly displayed image. If one loads local images into JOSM which are stored locally it has these functionality.

**Comment by drkludge** [comment]
It would be great if you'd leverage or better yet merge the operations of the GeoTagged image plugin with the OSV plugin.  The jump to blue and jump to red would be a great feature too.

![image](https://cloud.githubusercontent.com/assets/1669057/17458817/f407099c-5bd4-11e6-87d0-4287c8931bcc.png)

**Comment by beataj-telenav** [comment]
Feature was implemented.
