### ISSUE TITLE
JOSM Plugin to Show Camera Orientation 

### ISSUE THREAD

**Issue by MikeTho16** [openstreetview/josm-plugin#3]
It would be very helpful if the JOSM plugin showed the direction/orientation the camera was pointed when the photo was taken. Even if this is simply inferred from the direction of travel, this would be beneficial when mapping from these photos. One way to do this would be to add a little arrow head to the OpenStreetView icon that is shown on the map in JOSM.

**Comment by beataj-telenav** [comment]
Thanks for the suggestion. We plan to show also the track direction for the next version of the plugin.

**Comment by james2432** [comment]
This would be useful as I am taking side shots and knowing the compass direction would save time from clicking the wrong one

**Comment by baditaflorin** [comment]
+1 on this

**Comment by beataj-telenav** [comment]
This feature was implemented,
