### ISSUE TITLE
State Of The Map "Editor"

### ISSUE THREAD

**Issue by drkludge** [openstreetview/josm-plugin#7]
[It was unclear to me where this "editor" is located](https://youtu.be/XuGjahx8CFc?t=661).  Is this another tool that I download and run that is not part of JOSM; it is in JOSM; or the tool is on the website?  The video url is at the point the tool is discussed.

**Comment by bogdans-telenav** [comment]
@drkludge at least for now the "editor" that you are talking about is not made public as you can see from the repo https://github.com/openstreetview/editor

**Comment by martijnv-telenav** [comment]
We'll have more news probably around SOTM International. I'll close this ticket here. Thanks for your patience!
