### ISSUE TITLE
Only load images within data extent

### ISSUE THREAD

**Issue by martijnv-telenav** [openstreetview/josm-plugin#8]
See how the Mapillary plugin does this nicely:

![](https://www.dropbox.com/s/foing1gbiuxhulj/Screenshot%202016-09-01%2016.33.14.png?dl=1)

instead of taking the viewport we should use the active data layer's extent as you see above, avoiding loading unneeded images.

**Comment by beataj-telenav** [comment]
This is a good idea, thanks for your suggestion.

**Comment by beataj-telenav** [comment]
This feature was implemented.
